/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceRequired = IDL.Variant({
  'bondCleaning' : IDL.Null,
  'bathroomToiletCleaning' : IDL.Null,
  'windowCleaning' : IDL.Null,
  'generalEnquiry' : IDL.Null,
  'wallSpotCleaning' : IDL.Null,
  'carpetSteamCleaning' : IDL.Null,
  'ovenKitchenCleaning' : IDL.Null,
});
export const Time = IDL.Int;
export const Enquiry = IDL.Record({
  'id' : IDL.Nat,
  'serviceRequired' : ServiceRequired,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getEnquiriesByService' : IDL.Func(
      [ServiceRequired],
      [IDL.Vec(Enquiry)],
      ['query'],
    ),
  'getEnquiryById' : IDL.Func([IDL.Nat], [Enquiry], ['query']),
  'getSubmissionCount' : IDL.Func([], [IDL.Nat], ['query']),
  'submitEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ServiceRequired, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceRequired = IDL.Variant({
    'bondCleaning' : IDL.Null,
    'bathroomToiletCleaning' : IDL.Null,
    'windowCleaning' : IDL.Null,
    'generalEnquiry' : IDL.Null,
    'wallSpotCleaning' : IDL.Null,
    'carpetSteamCleaning' : IDL.Null,
    'ovenKitchenCleaning' : IDL.Null,
  });
  const Time = IDL.Int;
  const Enquiry = IDL.Record({
    'id' : IDL.Nat,
    'serviceRequired' : ServiceRequired,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getEnquiriesByService' : IDL.Func(
        [ServiceRequired],
        [IDL.Vec(Enquiry)],
        ['query'],
      ),
    'getEnquiryById' : IDL.Func([IDL.Nat], [Enquiry], ['query']),
    'getSubmissionCount' : IDL.Func([], [IDL.Nat], ['query']),
    'submitEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ServiceRequired, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };