/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Enquiry {
  'id' : bigint,
  'serviceRequired' : ServiceRequired,
  'name' : string,
  'email' : string,
  'message' : string,
  'address' : string,
  'timestamp' : Time,
  'phone' : string,
}
export type ServiceRequired = { 'bondCleaning' : null } |
  { 'bathroomToiletCleaning' : null } |
  { 'windowCleaning' : null } |
  { 'generalEnquiry' : null } |
  { 'wallSpotCleaning' : null } |
  { 'carpetSteamCleaning' : null } |
  { 'ovenKitchenCleaning' : null };
export type Time = bigint;
export interface _SERVICE {
  'getAllEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getEnquiriesByService' : ActorMethod<[ServiceRequired], Array<Enquiry>>,
  'getEnquiryById' : ActorMethod<[bigint], Enquiry>,
  'getSubmissionCount' : ActorMethod<[], bigint>,
  'submitEnquiry' : ActorMethod<
    [string, string, string, string, ServiceRequired, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];