/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Enquiry {
    id: bigint;
    serviceRequired: ServiceRequired;
    name: string;
    email: string;
    message: string;
    address: string;
    timestamp: Time;
    phone: string;
}
export enum ServiceRequired {
    bondCleaning = "bondCleaning",
    bathroomToiletCleaning = "bathroomToiletCleaning",
    windowCleaning = "windowCleaning",
    generalEnquiry = "generalEnquiry",
    wallSpotCleaning = "wallSpotCleaning",
    carpetSteamCleaning = "carpetSteamCleaning",
    ovenKitchenCleaning = "ovenKitchenCleaning"
}
export interface backendInterface {
    getAllEnquiries(): Promise<Array<Enquiry>>;
    getEnquiriesByService(service: ServiceRequired): Promise<Array<Enquiry>>;
    getEnquiryById(id: bigint): Promise<Enquiry>;
    getSubmissionCount(): Promise<bigint>;
    submitEnquiry(name: string, email: string, phone: string, address: string, serviceRequired: ServiceRequired, message: string): Promise<bigint>;
}
import type { Enquiry as _Enquiry, ServiceRequired as _ServiceRequired, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllEnquiries(): Promise<Array<Enquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEnquiries();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEnquiries();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEnquiriesByService(arg0: ServiceRequired): Promise<Array<Enquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnquiriesByService(to_candid_ServiceRequired_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnquiriesByService(to_candid_ServiceRequired_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEnquiryById(arg0: bigint): Promise<Enquiry> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnquiryById(arg0);
                return from_candid_Enquiry_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnquiryById(arg0);
            return from_candid_Enquiry_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmissionCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionCount();
            return result;
        }
    }
    async submitEnquiry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ServiceRequired, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitEnquiry(arg0, arg1, arg2, arg3, to_candid_ServiceRequired_n6(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitEnquiry(arg0, arg1, arg2, arg3, to_candid_ServiceRequired_n6(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
}
function from_candid_Enquiry_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Enquiry): Enquiry {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceRequired_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceRequired): ServiceRequired {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    serviceRequired: _ServiceRequired;
    name: string;
    email: string;
    message: string;
    address: string;
    timestamp: _Time;
    phone: string;
}): {
    id: bigint;
    serviceRequired: ServiceRequired;
    name: string;
    email: string;
    message: string;
    address: string;
    timestamp: Time;
    phone: string;
} {
    return {
        id: value.id,
        serviceRequired: from_candid_ServiceRequired_n4(_uploadFile, _downloadFile, value.serviceRequired),
        name: value.name,
        email: value.email,
        message: value.message,
        address: value.address,
        timestamp: value.timestamp,
        phone: value.phone
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bondCleaning: null;
} | {
    bathroomToiletCleaning: null;
} | {
    windowCleaning: null;
} | {
    generalEnquiry: null;
} | {
    wallSpotCleaning: null;
} | {
    carpetSteamCleaning: null;
} | {
    ovenKitchenCleaning: null;
}): ServiceRequired {
    return "bondCleaning" in value ? ServiceRequired.bondCleaning : "bathroomToiletCleaning" in value ? ServiceRequired.bathroomToiletCleaning : "windowCleaning" in value ? ServiceRequired.windowCleaning : "generalEnquiry" in value ? ServiceRequired.generalEnquiry : "wallSpotCleaning" in value ? ServiceRequired.wallSpotCleaning : "carpetSteamCleaning" in value ? ServiceRequired.carpetSteamCleaning : "ovenKitchenCleaning" in value ? ServiceRequired.ovenKitchenCleaning : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Enquiry>): Array<Enquiry> {
    return value.map((x)=>from_candid_Enquiry_n2(_uploadFile, _downloadFile, x));
}
function to_candid_ServiceRequired_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceRequired): _ServiceRequired {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceRequired): {
    bondCleaning: null;
} | {
    bathroomToiletCleaning: null;
} | {
    windowCleaning: null;
} | {
    generalEnquiry: null;
} | {
    wallSpotCleaning: null;
} | {
    carpetSteamCleaning: null;
} | {
    ovenKitchenCleaning: null;
} {
    return value == ServiceRequired.bondCleaning ? {
        bondCleaning: null
    } : value == ServiceRequired.bathroomToiletCleaning ? {
        bathroomToiletCleaning: null
    } : value == ServiceRequired.windowCleaning ? {
        windowCleaning: null
    } : value == ServiceRequired.generalEnquiry ? {
        generalEnquiry: null
    } : value == ServiceRequired.wallSpotCleaning ? {
        wallSpotCleaning: null
    } : value == ServiceRequired.carpetSteamCleaning ? {
        carpetSteamCleaning: null
    } : value == ServiceRequired.ovenKitchenCleaning ? {
        ovenKitchenCleaning: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
